[project]
name = "old-gc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "geopandas>=1.1.2",
    "gerrychain[geo]>=0.3.2",
    "ipykernel>=7.1.0",
    "ipython>=9.9.0",
    "pandas>=3.0.0",
]
